### ISSUE TITLE
Fritzing is broken

### ISSUE THREAD

**Issue by THS-on** [imedias/lernstick-desktop-file-diversions#3]
In Debian 9 Fritzing is broken.
The package ` fritzing-parts` must also be installed because there are no parts provided by default.
To really use the UI of Fritzing `QT_AUTO_SCREEN_SCALE_FACTOR=0` must be set because otherwise the fonts are too big.

**Comment by ronnystandtke** [comment]
Including fritzing-parts is fixed here: [https://github.com/imedias/lernstickAdvanced/commit/ba3d05b2f8f0e45331efd8881f5a7bed4ef642ef](https://github.com/imedias/lernstickAdvanced/commit/ba3d05b2f8f0e45331efd8881f5a7bed4ef642ef)
(Un)fortunately, I could not reproduce the font issue...

**Comment by THS-on** [comment]
Please try on real hardware.  There was no issue in VirtualBox but on my machine (1920x1080) 
Have a look at https://github.com/fritzing/fritzing-app/issues/3221

![fritzing](https://user-images.githubusercontent.com/10854414/27920714-ce3cd6f8-6275-11e7-9a66-b0c76fbc7aa8.png)
The window in the middle is with `QT_AUTO_SCREEN_SCALE_FACTOR=0` and the other one without. Without this fix Fritzing is not usable on my machine.

**Comment by ronnystandtke** [comment]
fixed in commit https://github.com/imedias/lernstick-desktop-file-diversions/commit/e1da8705ecfebe36f5ef0e8650cfbfb5eb80d95f
